### ISSUE TITLE
Should I see the two zones and purple lines by default?

### ISSUE THREAD

**Issue by pglpm** [szermatt/mistty#2]
Hi! I'm very curious to try Mistty. I'm on Emacs 29.1, Ubuntu 20.04, KDE/Plasma 5. Other Emacs config options:

`./configure --with-native-compilation --with-json --enable-link-time-optimization --with-x-toolkit=lucid --without-toolkit-scroll-bars`

Installed Mistty from `package-list-packages`, and installation didn't give any warnings. Also restarted Emacs.

When I launch Mistty with `M-x mistty` I get the view shown in the snaphshot below. Most notably I don't see the two "zones" or purple line mentioned in the Mistty manual. I see that I can send bash commands and they get executed. But it seems something isn't quite as described. Have checked through some chapters in the manual but can't find any hints. My bash shell is in emacs-edit mode.

I appreciate if someone tells me whether what I'm seeing looks correct or not :)

![Screenshot_20230924_175527](https://github.com/szermatt/mistty/assets/9976691/8ff4af87-02ef-44a3-9e63-eeb66af47e57)

**Comment by szermatt** [comment]
It seems ok. The purple line on the left is there, it's just very subtle.  

There's only one zone for now, because you haven't executed anything. Try executing a ls with a long output and you should see that the purple line on the left doesn't cover the entire buffer anymore. 

The real test, of course, is:
- whether you can use Emacs commands to edit the command line, maybe try and do something like a hippie completion or a yank.
- whether you can use shell commands, maybe try pressing TAB

**Comment by pglpm** [comment]
Thank you for such a prompt help! Below is a screenshot of what I see with a `ls`. I also tried it in a directory with many more entries, and it looks the same, except that the buffer scrolls.

- Copy and yank seems to work (I use `CUA` mode)

- TAB also seems to work as in bash, e.g. completing the name of files or directories.

![Screenshot_20230924_184139](https://github.com/szermatt/mistty/assets/9976691/233aeeed-41cb-4db1-bbd6-88a75edf1680)

**Comment by szermatt** [comment]
Yes, it looks like it works, then. No problems. 

It does look different from the manual, because we're using different themes, shells and prompts. 

I suspect you're using a version of bash < 5. This is why you're not seeing the purple line only on the prompt, as on the screenshots. It should also work, but not as well as bash 5 would. In particular, I fear that multiline editing as described in the manual, with shift-return, won't work with bash 4. I'll update the manual. 

It might be a good idea, if you can, to upgrade to bash 5.

**Comment by szermatt** [comment]
If you're using bash 4.4 or later, it might be a good idea to add the following to your .inputrc:

```
set enable-bracketed-paste on
```

**Comment by pglpm** [comment]
Thank you for the extra help! I'm using bash 5.0.17. I've now added the `set` you recommended. Looking forward to use Mistty, thank you for your work!
