### ISSUE TITLE
Line unwrapping broken after window widening

### ISSUE THREAD

**Issue by dcolascione** [szermatt/mistty#24]
`term` does something funky with line wrapping that I don't yet fully understand that results in `end-of-line` moving to the wrong spot in missy in windows wider than they were at time of line emission. To repro:

  1. start mistty
  2. make the window pretty narrow
  3. output a long line that'll wrap (in a POSIX shell, you can write something like `for ((i=0; i<30; ++i)); do printf "XXXXXXX"; done; echo Y`)
  4. move point to start of line
  5. Press `C-e`
  6. Observe point go to end of line
  7. Go back to the start of the line
  8. Widen the window; line should be unwrapped
  9. Press `C-e` again

Expected behavior: point goes to new, post-window-resize, line ending point
Actual behavior: point goes to where it did before window resize

The problem seems to have something to do with `term` "unwrapping" the line by making `\n` invisible instead of just deleting it. In `term` itself, I can't reproduce the above behavior, but in `mistty`, I can.

**Comment by szermatt** [comment]
Thank you for the report! 

This is a weird behavior. Unfortunately, I haven't been able to reproduce it yet. 

To be sure I understood, this all happening on the prompt, the terminal zone. What's really surprising is that in the terminal zone "C-e" is supposed to be controlled by the shell. That is, "C-e" is simply sent to the shell, which then does whatever it wants with it. The shell would not be confused by invisible `\n` introduced by term, but it could disagree on how wide the terminal currently is. It is possible that "C-e" is not bound as it should to `mistty-end-of-line-or-goto-cursor` at the point you're calling it?

I'm afraid I'll need some more help to figure out what's happening:
- What version of Emacs are you using?
- What OS?
- What shell are you using? What version?
- What is the expected behavior of C-e on your shell on a multi-line prompt? Should it go to the end of the prompt or the end of the current line?
- Are you running Emacs on a terminal or in a window?
- Could you run `M-x mistty-start-log`, reproduce the problem and then attach the content of the `*mistty-log*` buffer to this issue? This buffer would show all the communication that happened between Emacs and the shell. (This might be better described [in the doc](https://mistty.readthedocs.io/en/latest/contrib.html#reporting-issues))

Thanks!

**Comment by dcolascione** [comment]
C-e has its default binding. I've also tried just running end-of-line locally. One thing I should have mentioned: the text I'm navigating is *outside* the shell region, not inside it, so the shell shouldn't be involved here at all.

**Comment by dcolascione** [comment]
BTW: this hack (I know it's not the right fix) at least unblocks me

```
diff --git a/mistty/mistty.el b/mistty/mistty.el
index 79ef9853d7..ca6e157273 100644
--- a/mistty/mistty.el
+++ b/mistty/mistty.el
@@ -1286,6 +1286,13 @@ Also updates prompt and point."
            (goto-char mistty-sync-marker)
            (while-let ((prop-match
                         (text-property-search-forward 'term-line-wrap t t)))
+             ;; TODO(dancol): remove temporary hack that solves the
+             ;; mistty bug we shouldn't be keeping these fake newline
+             ;; characters in there at all!
+             (save-excursion
+               (goto-char (prop-match-beginning prop-match))
+               (delete-char 1)
+               (insert "!"))
              (put-text-property (prop-match-beginning prop-match)
                                 (prop-match-end prop-match)
                                 'invisible 'term-line-wrap)))
```

I tried just deleting the newline instead of making it invisible, but doing that messes up some kind of internal bookkeeping.

**Comment by szermatt** [comment]
> the text I'm navigating is outside the shell region, not inside it, so the shell shouldn't be involved here at all.

Ah, so I misunderstood!
 
I can reproduce it, now. It shouldn't be too hard to fix.
